spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/Task
spring.datasource.username=postgres
spring.datasource.password=vsb123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


